version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
     - checkout
     - run:
          name: Build docker container for each microservices
          command: |
            curl -fsSl https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node -v
            npm -v
            docker-compose -f docker-compose-build.yaml build --parallel

            docker tag udagram-api-feed:v1a $DOCKER_USERNAME/udagram-api-feed:v1

            docker tag udagram-api-user:v1a $DOCKER_USERNAME/udagram-api-user:v1

            docker tag udagram-frontend:local $DOCKER_USERNAME/udagram-frontend:v1

            docker tag reverseproxy:v1a $DOCKER_USERNAME/reverseproxy:v1

            echo "-----------All images successfully built-----------"

            echo "-----------login in to hub--------------"

            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            echo "----------Pushing images to dockerhub----------"

            docker push $DOCKER_USERNAME/udagram-api-feed:v1
            docker push $DOCKER_USERNAME/udagram-api-user:v1
            docker push $DOCKER_USERNAME/udagram-frontend:v1
            docker push $DOCKER_USERNAME/reverseproxy:v1

workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]
    